### ISSUE TITLE
focus in not coming directly when perfroming segue to another view controller 

### ISSUE THREAD

**Issue by sohail19** [PetecOvod/MYPassthrough#3]
rotationTask.didFinishTask = {
			self.performSegue(withIdentifier: "contactsSegue", sender: nil)
}

**Comment by PetecOvod** [comment]
@sohail19  thank you for this issue. In order to focus on view, you must provide a reference to the object from the controller. As far as I understand you want to add all the tasks from one controller but then you will not be able to give reference to the view from other controllers (for example, controller which open using segue). I suggest you divide the task into several stages. One of the possible implementation I made in the branch 'develop/extendedExample'. 
Please let me know if this resolves your question or provide a more detailed description of the problem.

**Comment by Raihan-iOS** [comment]
Not cover frame exact location. When app uninstall and install again its not work at all . 
**Code:**
`  override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        appleImage.layer.cornerRadius = appleImage.layer.frame.height/2
        if launchedBefore == false{
            PassthroughManager.shared.closeButton.setTitle("Skip", for: .normal)
            createDemoHandlersOfTask()
        }
        
    }
    
    
    func createDemoHandlersOfTask() {
        
        let imageDescriptor  = LabelDescriptor(for: "Fruit Image")
        imageDescriptor.position = .top
        let imageHoleDescriptor = HoleDescriptor(frame: appleImage.frame, type: .circle, forOrientation: .portrait)//rect(cornerRadius: 2, margin: 4), forOrientation: .portrait)
        imageHoleDescriptor.labelDescriptor = imageDescriptor
        let task1 = PassthroughTask(with: [imageHoleDescriptor])

        
        let nameDescriptor  = LabelDescriptor(for: "Fruit Name")
        nameDescriptor.position = .bottom
        let nameHoleDescriptor = HoleDescriptor(frame: fruitName.frame, type: .rect(cornerRadius: 2, margin: 0), forOrientation: .portrait)
        nameHoleDescriptor.labelDescriptor = nameDescriptor
        let task2 = PassthroughTask(with: [nameHoleDescriptor])


        let originDescriptor  = LabelDescriptor(for: "Country Origin")
        originDescriptor.position = .bottom
        let originHoleDescriptor = HoleDescriptor(frame: fruitOrigin.frame, type: .rect(cornerRadius: 2, margin: 0), forOrientation: .portrait)
        originHoleDescriptor.labelDescriptor = originDescriptor
        let task3 = PassthroughTask(with: [originHoleDescriptor])

        let descriptionDescriptor  = LabelDescriptor(for: "Fruit Description")
        descriptionDescriptor.position = .bottom
        let descriptionHoleDescriptor = HoleDescriptor(frame: fruitDescription.frame, type: .rect(cornerRadius: 2, margin: 0), forOrientation: .portrait)
        descriptionHoleDescriptor.labelDescriptor = descriptionDescriptor
        let task4 = PassthroughTask(with: [descriptionHoleDescriptor])


        let qauntityViewDescriptor  = LabelDescriptor(for: "Fruit Quantity")
        qauntityViewDescriptor.position = .bottom
        let qauntityViewDescriptorHoleDescriptor = HoleDescriptor(frame: quantityView.frame, type: .rect(cornerRadius: 2, margin: 0), forOrientation: .portrait)
        qauntityViewDescriptorHoleDescriptor.labelDescriptor = qauntityViewDescriptor
        let task5 = PassthroughTask(with: [qauntityViewDescriptorHoleDescriptor])



        let labelDescriptor = LabelDescriptor(for: "Buy Button")
        labelDescriptor.position = .top
        let holeDescriptor = HoleDescriptor(frame: testButton.frame, type: .rect(cornerRadius: 2, margin: 0), forOrientation: .portrait)
        holeDescriptor.labelDescriptor = labelDescriptor
        let task6 = PassthroughTask(with: [holeDescriptor])

        
         PassthroughManager.shared.display(tasks: [task1,task2,task3,task4,task5,task6])
        
    }`
